language: go

go:
  - 1.9.x
  - 1.10.x
  - master

matrix:
  allow_failures:
    - go: master

before_install:
  - go get -u github.com/vbatts/git-validation
  - go get -u github.com/golang/lint/golint

script:
  - make ci
